# Generated by Django 2.2.3 on 2019-07-22 07:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.PositiveIntegerField(choices=[(1, 'Standard'), (2, 'VIP')], default=1)),
                ('occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_reg_no', models.CharField(max_length=8)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.Slot')),
            ],
        ),
    ]
