# Generated by Django 2.2.3 on 2019-07-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20190723_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alloted_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
