# Generated by Django 2.2.3 on 2019-07-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_customer_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['entry_time']},
        ),
    ]
