# Generated by Django 2.2.3 on 2019-07-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20190724_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notification_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
