# Generated by Django 2.2.3 on 2019-07-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_customer_notification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
