# Generated by Django 2.2.3 on 2019-07-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_email', models.EmailField(default='kamiljaved98@gmail.com', max_length=254)),
                ('auto_email', models.BooleanField(default=False)),
                ('num_standard_slots', models.PositiveIntegerField(default=27)),
                ('num_vip_slots', models.PositiveIntegerField(default=27)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
