# Generated by Django 2.2.3 on 2019-07-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='auto_email',
            field=models.BooleanField(default=False, verbose_name='Auto-Mail Daily Record'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_email',
            field=models.EmailField(default='kamiljaved98@gmail.com', max_length=254, verbose_name='Default Email'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='num_standard_slots',
            field=models.PositiveIntegerField(default=27, verbose_name='No. of Standard Slots'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='num_vip_slots',
            field=models.PositiveIntegerField(default=27, verbose_name='No. of VIP Slots'),
        ),
    ]
