# Generated by Django 2.2.3 on 2019-07-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyrecord',
            options={'ordering': ['-created']},
        ),
    ]
