# Generated by Django 2.2.3 on 2019-07-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ready_to_show',
            field=models.BooleanField(default=False),
        ),
    ]
