# Generated by Django 2.2.3 on 2019-07-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20190723_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-updated']},
        ),
    ]
